site_name: EAD Notes
docs_dir: notes/
theme:
  name: material
  favicon: 'assets/images/java.png'
  logo: 'assets/images/java.png'
  palette:
    scheme: default
    primary: teal
    accent: teal
  font:
    text: Roboto
    code: Roboto Mono
  language: en
  features:
    # - header.autohide
    - navigation.tabs
    # - navigation.instant
  icon:
    repo: fontawesome/brands/github

copyright: Copyright &copy; 2022 Arjun Adhikari
repo_url: https://github.com/thearjun/ead-notes
repo_name: EAD Notes
edit_uri: "https://github.com/thearjun/ead-notes/tree/master/notes/"
markdown_extensions:
  - meta
  - abbr
  - admonition
  - pymdownx.details
  - attr_list
  - pymdownx.highlight:
      linenums_style: pymdownx.inline
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.tabbed
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols 
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
extra:
  generator: false
  manifest: manifest.webmanifest
  social:
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/thearjun
    - icon: fontawesome/brands/github
      link: https://github.com/thearjun
    - icon: fontawesome/solid/envelope
      link: mailto:mailarjunadhikari@gmail.com
    - icon: fontawesome/solid/user
      link: https://www.upwork.com/freelancers/~017a123f27939046d8

extra_javascript:
  - assets/javascripts/extra.js
  - assets/javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - assets/stylesheets/extra.css

plugins:
  - search
  # - with-pdf:
  #     author: Arjun Adhikari
  #     copyright: Copyright &copy; 2022 Arjun Adhikari
  #     cover: True
  #     cover_title: Enterprise Application Development Notes
  #     cover_subtitle: Notes for PU Syllabus
  #     toc_level: 3
  #     exclude_pages: 
  #       - '/'

  - macros:
      include_dir: notes
nav:
  - Introduction:
    - index.md
    - Enterprise Application Architecture: 
      - introduction/enterprise-application-architecture/introduction.md
      - Platform for Enterprise Solutions: introduction/enterprise-application-architecture/platform-for-enterprise-solutions.md
      - Enterprise Architecture Framework: introduction/enterprise-application-architecture/enterprise-application-framework.md
    - Web Technology Concepts:
      - Protocols: introduction/web-technologies-concepts/protocols.md
      - Communication Types: introduction/web-technologies-concepts/communication-types.md
      - Web Services: introduction/web-technologies-concepts/web-services.md
      - Data Exchange Formats: 
        - introduction/web-technologies-concepts/data-exchange-formats.md
        - Conversion between Data Exchange Formats: introduction/web-technologies-concepts/data-format-conversion.md

  - Development Process Management:
    - Source Code Management: development-process-management/source-code-management.md
    - Continuous Integration: development-process-management/continuous-integration.md
    - Software Testing: development-process-management/software-testing.md
    - Software Documentation: development-process-management/software-documentation.md

  - Design Patterns:
    - Introduction: design-patterns/introduction.md
    - Types of Patterns: design-patterns/types-of-patterns.md
    - Dependency Injection and Inversion of Control: design-patterns/di-and-ioc.md
    - Convention vs Configuration: design-patterns/convention-vs-configuration.md
    - Factory Pattern: design-patterns/factory-pattern.md
    - Singleton Pattern: design-patterns/singleton-pattern.md
    - Lazy Initialization: design-patterns/lazy-initialization.md

  - Web App Architecture:
    - Introduction: web-application-architecture/introduction.md
    - Layered Architecture: web-application-architecture/layered-architecture-for-web-applications.md
    - MVC Pattern: web-application-architecture/mvc-pattern.md

  - SOA and RESTful:
    - Introduction: soa-and-restful/introduction.md
    - Resource Oriented Architecture: soa-and-restful/resource-oriented-architecture.md
    - Analysis and Design:
      - Read Only Resource Oriented Services: soa-and-restful/roa-analysis-and-design/read-only.md
      - Read Write Resource Oriented Services: soa-and-restful/roa-analysis-and-design/read-write.md
  
  - Security:
    - software-security/introduction.md
    - Basic Attacks: software-security/basic-attacks.md
    - State Based Attacks: software-security/state-based-attacks.md
    - Client Side Authentication: software-security/client-side-authentication.md
    - Cross Site Scripting: software-security/cross-site-scripting.md
    - Denial of Service: software-security/dos.md
    - SQL Injection: software-security/sql-injection.md

  - Development Methodologies:
    - AGILE: 
      - Principles: software-development-methodologies/agile-principles.md
      - Methodologies : software-development-methodologies/agile-methodologies.md
    - Test Driven Development (TDD): software-development-methodologies/test-driven-development.md
    - Behaviour Driven Development (BDD): software-development-methodologies/behaviour-driven-development.md
  - Extras:
    - Questions: extra/questions/index.md
    - Abbreviations: extra/abbreviations.md
